"""Default corpus registry for azrael — Greek/Roman/Norse/Celtic/Egyptian source texts."""
AZRAEL_DEFAULT_CORPUSES = [
    {"id": "gutenberg-iliad",       "name": "The Iliad (Homer)",
     "source_type": "gutenberg",    "source": "2199",
     "topics": ["greek", "hero", "war"],
     "description": "Homer's Iliad — the Trojan War epic"},
    {"id": "gutenberg-odyssey",     "name": "The Odyssey (Homer)",
     "source_type": "gutenberg",    "source": "1727",
     "topics": ["greek", "hero", "journey"],
     "description": "Homer's Odyssey — the wanderings of Odysseus"},
    {"id": "gutenberg-theogony",    "name": "Theogony & Works and Days (Hesiod)",
     "source_type": "gutenberg",    "source": "348",
     "topics": ["greek", "deity", "creation", "cosmology"],
     "description": "Hesiod — Greek divine genealogy and creation"},
    {"id": "gutenberg-metamorphoses","name": "Metamorphoses (Ovid)",
     "source_type": "gutenberg",    "source": "26073",
     "topics": ["roman", "greek", "transformation", "deity"],
     "description": "Ovid — myths of transformation"},
    {"id": "gutenberg-aeneid",      "name": "The Aeneid (Virgil)",
     "source_type": "gutenberg",    "source": "227",
     "topics": ["roman", "hero", "troy"],
     "description": "Virgil — the founding of Rome"},
    {"id": "gutenberg-homeric-hymns","name": "Homeric Hymns",
     "source_type": "gutenberg",    "source": "24327",
     "topics": ["greek", "deity", "ritual"],
     "description": "Ancient hymns to the Greek gods"},
    {"id": "gutenberg-prose-edda",  "name": "Prose Edda (Snorri Sturluson)",
     "source_type": "gutenberg",    "source": "10782",
     "topics": ["norse", "deity", "creation", "cosmology"],
     "description": "Primary Norse mythology source"},
    {"id": "gutenberg-volsunga",    "name": "Volsunga Saga",
     "source_type": "gutenberg",    "source": "1152",
     "topics": ["norse", "hero", "dragon"],
     "description": "The Norse saga of the Volsung family"},
    {"id": "gutenberg-mabinogion",  "name": "The Mabinogion",
     "source_type": "gutenberg",    "source": "5765",
     "topics": ["celtic", "welsh", "hero", "faerie"],
     "description": "Welsh mythology — the four branches"},
    {"id": "gutenberg-celtic-myth", "name": "Celtic Myth and Legend (Squire)",
     "source_type": "gutenberg",    "source": "14672",
     "topics": ["celtic", "irish", "scottish"],
     "description": "Celtic mythology survey by Charles Squire"},
    {"id": "gutenberg-egyptian-myth","name": "Egyptian Myth and Legend (Mackenzie)",
     "source_type": "gutenberg",    "source": "15403",
     "topics": ["egyptian", "deity", "creation", "afterlife"],
     "description": "Egyptian mythology survey"},
    {"id": "gutenberg-1001-nights", "name": "One Thousand and One Nights",
     "source_type": "gutenberg",    "source": "34206",
     "topics": ["arabic", "persian", "tales", "djinn"],
     "description": "Arabian Nights — folk tales from the Islamic Golden Age"},
    {"id": "gutenberg-ramayana",    "name": "The Ramayana (Dutt translation)",
     "source_type": "gutenberg",    "source": "24869",
     "topics": ["hindu", "hero", "deity"],
     "description": "Hindu epic — Rama's quest to rescue Sita"},
    {"id": "gutenberg-mahabharata", "name": "The Mahabharata (Ganguli translation)",
     "source_type": "gutenberg",    "source": "15474",
     "topics": ["hindu", "hero", "deity", "war"],
     "description": "Hindu epic — the Kurukshetra war"},
]
